version: '3.9'

services:
  database_server:
    image: mongo:6-jammy
    ports:
      - 27017:27017
    volumes:
      - vol_database:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run server
    ports:
      - 5000:5000
    depends_on:
      - database_server
    environment:
      MONGO_URI: "mongodb://database_server:27017/my_database"

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./client
    command: npm run start
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - server
    ports:
      - 3000:3000
    environment:
      REACT_APP_PROXY: "http://server:5000"

volumes:
  vol_database: