spring:
  application:
    name: apukeeper
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:apukeeper
    password:
    username: sa
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /console/
      settings:
        web-allow-others: true